### ISSUE TITLE
Test set evaluation

### ISSUE THREAD

**Issue by ssusie** [daviswer/fewshotlocal#2]
Hello,

The Evaluate.ipynb still uses repr and query data. I am wondering where you actually used test data for evaluation and whether there is a code for visualizing results on some images.

Thanks.

**Comment by daviswer** [comment]
Hello! The repr and query directories collectively contain all of the test images - they're partitions of the test set. So when the Evaluate notebook uses repr and query, that's the test data. The fact that /test, /repr, and /query are distinct directories, despite their overlapping content, is mostly an artifact of our early sandbox code. 

Code exists for visualizing network outputs, but it's not compatible with the public code available here. We had to re-work everything significantly so that we could have a single wrapper for all 12 possible models, and anything non-essential was dropped. You could certainly extract and modify some of the accumulation functions from helpful_files/testing.py to do that, though - displaying individual outputs rather than accumulating them.

**Comment by ssusie** [comment]
Thanks a lot for your prompt reply and explanations! 

I will give it a try.
